export enum Country {
  MX = 'Mexique',
  EE = 'Estonie',
  DZ = 'Algérie',
  MA = 'Maroc',
  MR = "Mauritanie",
  SN = "Sénégal",
  GM = "Gambie",
  GW = "Guinée-Bissau",
  GN = "Guinée",
  SL = "Sierra Leone",
  LR = "Libéria",
  CI = "Côte d'Ivoire",
  ML = "Mali",
  BF = "Burkina Faso",
  NE = "Niger",
  GH = "Ghana",
  TG = "Togo",
  BJ = "Bénin",
  NG = "Nigeria",
  TN = "Tunisie",
  LY = "Libye",
  EG = "Egypte",
  TD = "Tchad",
  SS = "Soudan du Sud",
  SD = "Soudan",
  CM = "Cameroun",
  ER = "Érythrée",
  DJ = "Djibouti",
  ET = "Éthiopie",
  SO = "Somalie",
  CF = "République centrafricaine",
  ST = "Sao Tomé-et-Principe",
  GA = "Gabon",
  GQ = "Guinée équatoriale",
  CG = "République du Congo",
  CD = "République démocratique du Congo",
  RW = "Rwanda",
  BI = "Burundi",
  UG = "Ouganda",
  KE = "Kenya",
  TZ = 'Tanzanie',
  ZM = 'Zambie',
  AO = 'Angola',
  MW = 'Malawi',
  MZ = 'Mozambique',
  ZW = 'Zimbabwe',
  NA = 'Namibie',
  BW = 'Botswana',
  SZ = 'Swaziland',
  LS = 'Lesotho',
  ZA = "Afrique du Sud",
  GL = "Groenland",
  AQ = "Antarctique",
  AU = "Australie",
  NZ = "Nouvelle-Zélande",
  NC = "Nouvelle-Calédonie",
  ID = "Indonésie",
  BN = "Brunei",
  TL = "Timor-Leste",
  PG = "Papouasie-Nouvelle-Guinée",
  SB = "Îles Salomon",
  VU = "Vanuatu",
  FJ = "Fidji",
  PH = "Philippines",
  TW = "Taïwan",
  JP = "Japon",
  MU = "Île Maurice",
  RE = "La Réunion",
  MG = "Madagascar",
  KM = "Comores",
  YT = "Mayotte",
  SC = "Seychelles",
  MV = "Maldives",
  CV = "Cap-Vert",
  PF = "Polynésie française",
  GP = "Guadeloupe",
  DM = "Dominique",
  MQ = "Martinique",
  LC = "Sainte-Lucie",
  VC = "Saint-Vincent et les Grenadines",
  GD = "Grenade",
  TT = "Trinité-et-Tobago",
  PR = "Porto Rico",
  DO = "République Dominicaine",
  HT = "Haïti",
  FK = "Îles Falkland",
  IS = "Islande",
  LK = "Sri Lanka",
  CU = "Cuba",
  BS = "Bahamas",
  JM = "Jamaïque",
  CA = "Canada",
  US = "États-Unis",
  GT = "Guatemala",
  HN = "Honduras",
  SV = "El Salvador",
  NI = "Nicaragua",
  CR = "Costa Rica",
  PA = "Panama",
  CO = "Colombie",
  VE = "Venezuela",
  GY = "Guyane",
  SR = "Suriname",
  GF = "Guyane française",
  EC = "Equateur",
  PE = "Pérou",
  BO = "Bolivie",
  PY = "Paraguay",
  UY = "Uruguay",
  AR = "Argentine",
  CL = "Chili",
  BR = "Brésil",
  BZ = "Belize",
  RU = "Russie",
  CN = "Chine",
  MN = "Mongolie",
  KP = "Corée du Nord",
  KR = "Corée du Sud",
  KZ = "Kazakhstan",
  TM = "Turkménistan",
  UZ = "Ouzbékistan",
  TJ = "Tadjikistan",
  KG = "Kirghizistan",
  AF = "Afghanistan",
  PK = "Pakistan",
  IN = "Inde",
  NP = "Népal",
  BT = "Bhoutan",
  BD = "Bangladesh",
  MM = "Myanmar",
  TH = "Thaïlande",
  MY = "Malaisie",
  KH = "Cambodge",
  LA = "Laos",
  VN = "Vietnam",
  GE = "Géorgie",
  AM = "Arménie",
  AZ = "Azerbaïdjan",
  IR = "Iran",
  TR = "Turquie",
  YE = "Yémen",
  OM = "Oman",
  AE = "Émirats Arabes Unis",
  QA = "Qatar",
  KW = "Koweït",
  SA = "Arabie Saoudite",
  SY = "Syrie",
  IQ = "Irak",
  JO = "Jordanie",
  LB = "Liban",
  IL = "Israël",
  CY = "Chypre",
  NO = "Norvège",
  ENG = "Angleterre",
  WLS = "Pays de Galles",
  SCT = "Écosse",
  NIR = "Irlande du Nord",
  IE = "Irlande",
  SE = "Suède",
  FI = "Finlande",
  LV = "Lettonie",
  LT = "Lituanie",
  BY = "Biélorussie",
  PL = "Pologne",
  ES = "Espagne",
  ESC = "Îles Canaries",
  PT = "Portugal",
  PTA = "Açores",
  PTM = "Madère",
  FR = "France",
  NL = "Pays-Bas",
  BE = "Belgique",
  DE = "Allemagne",
  DK = "Danemark",
  CH = "Suisse",
  CZ = "République Tchèque",
  SK = "Slovaquie",
  AT = "Autriche",
  HU = "Hongrie",
  SI = "Slovénie",
  HR = "Croatie",
  BA = "Bosnie-Herzégovine",
  IT = "Italie",
  MT = "Malte",
  UA = "Ukraine",
  MD = "Moldavie",
  RO = "Roumanie",
  ME = "Monténégro",
  RS = "Serbie",
  BG = "Bulgarie",
  AL = "Albanie",
  MK = "Macédoine du Nord",
  GR = "Grèce",
  AX = "Åland",
  AS = "Samoa américaines",
  AD = "Andorre",
  VI = "Îles Vierges des États-Unis",
  VG = "Îles Vierges britanniques",
  MS = "Montserrat",
  AG = "Antigua-et-Barbuda",
  KN = "Saint-Christophe-et-Niévès",
  AI = "Anguilla",
  AW = "Aruba",
  BH = "Bahreïn",
  BB = "Barbade",
  BM = "Bermudes",
  CW = "Curaçao",
  KY = "Îles Caïmans",
  WS = "Samoa",
  CK = "Îles Cook",
  FO = "Îles Féroé",
  GI = "Gibraltar",
  GU = "Guam",
  MP = "Îles Mariannes du Nord",
  JE = "Jersey",
  GG = "Guernesey",
  HK = "Hong Kong",
  IM = "Île de Man",
  KI = "Kiribati",
  XK = "Kosovo",
  LI = "Liechtenstein",
  LU = "Luxembourg",
  MO = "Macao",
  MH = "Îles Marshall",
  FM = "Micronésie",
  MC = "Monaco",
  NR = "Nauru",
  NU = "Niué",
  PW = "Palaos",
  PS = "Palestine",
  SM = "Saint-Marin",
  SG = "Singapour",
  SX = "Sint Maarten",
  TO = "Tonga",
  TC = "Îles Turks et Caïques",
  TV = "Tuvalu",
  VA = "Vatican",
  WF = "Wallis et Futuna",
  EH = "Sahara Occidental",
  PI = "Îles Pitcairn",
  GS = "Géorgie du Sud et les Îles Sandwich du Sud",
  TB = "Territoire britannique de l'Océan Indien",
  HE = "Sainte-Hélène",
  SOM = "Somaliland",
  CIS = "Cisjordanie",
  SPM = "Saint-Pierre-et-Miquelon",
  TAF = "Terres australes et antarctiques françaises",
  CYN = "Chypre du Nord",
  HM = "Îles Heard et McDonald",
  NF = "Îles Norfolk",
  AC = "Îles Ashmore-et-Cartier",
  SIA = "Glacier Siachen",
  SBA = "Saint-Barthélemy",
  SMA = "Saint-Martin",
  CHR = "Île Christmas",
  COC = "Îles Cocos",
  IA = "Îles Aléoutiennes",
  TK = "Tokelau",
  BON = "Bonaire",
  STE = "Saint-Eustache",
  SAB = "Saba"
}


export interface TrainingSessionType {
  code: string;
  allowedPlans: ('RUNNING' | 'TRAIL' | 'FITNESS' | 'OTHER')[];
  category: string;
}

export const TRAINING_SESSION_TYPES: TrainingSessionType[] = [
  // Endurance & récupération
  { code: 'EF', allowedPlans: ['RUNNING', 'TRAIL', 'FITNESS', 'OTHER'], category: 'endurance' },
  { code: 'LONG_RUN', allowedPlans: ['RUNNING', 'TRAIL', 'FITNESS', 'OTHER'], category: 'endurance' },
  { code: 'RECOVERY', allowedPlans: ['RUNNING', 'TRAIL', 'FITNESS', 'OTHER'], category: 'endurance' },
  { code: 'RACE', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'endurance' },

  // Fractionné & intensité
  { code: 'SHORT_INTERVALS', allowedPlans: ['RUNNING', 'TRAIL', 'FITNESS', 'OTHER'], category: 'intensite' },
  { code: 'LONG_INTERVALS', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'intensite' },
  { code: 'PYRAMID', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'intensite' },
  { code: 'INTERVALS', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'intensite' },
  { code: 'VMA', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'intensite' },

  // Seuil & allures spécifiques
  { code: 'SEUIL', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'specific' },
  { code: 'TEMPO', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'specific' },
  { code: 'AS5', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'specific' },
  { code: 'AS10', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'specific' },
  { code: 'AS21', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'specific' },
  { code: 'AS42', allowedPlans: ['RUNNING', 'TRAIL', 'OTHER'], category: 'specific' },

  // Trail / dénivelé
  { code: 'SHORT_HILLS', allowedPlans: ['TRAIL', 'OTHER'], category: 'trail' },
  { code: 'LONG_HILLS', allowedPlans: ['TRAIL', 'OTHER'], category: 'trail' },
  { code: 'HILL_INTERVALS', allowedPlans: ['TRAIL', 'OTHER'], category: 'trail' },
  { code: 'DOWNHILL', allowedPlans: ['TRAIL', 'OTHER'], category: 'trail' },
  { code: 'HILLY_RUN', allowedPlans: ['TRAIL', 'OTHER'], category: 'trail' },

  // Renforcement
  { code: 'STRENGTH', allowedPlans: ['RUNNING', 'TRAIL', 'FITNESS', 'OTHER'], category: 'renfo' },
  { code: 'PPG', allowedPlans: ['RUNNING', 'TRAIL', 'FITNESS', 'OTHER'], category: 'renfo' },
];